In [8]:
import torch

sign = torch.sign(torch.tensor([0.0, 2.0, -3.0]))  # tensor([ 0.,  1., -1.])
sign

tensor([ 0.,  1., -1.])

In [9]:
import os, sys
if'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:  
    sys.exit("please declare environmentvariable 'SUMO_HOME'")

import sumolib

net = sumolib.net.readNet('data/smwan1.net.xml', withLatestPrograms=True)

In [10]:
tls = net.getTLS("J2")
tls_program = tls.getPrograms()["0"]

In [11]:
tls_program.getPhases()
inlines = list(set([c[0] for c in tls.getConnections()]))
inlines[0].getOutgoing()[0].getDirection()

's'

In [16]:
net.getTrafficLights()[0].getPrograms()["0"].getPhases()

[Phase(duration=38, state='rrrGGGgGGGg', minDur=-1, maxDur=-1),
 Phase(duration=3, state='rrryyygyyyg', minDur=-1, maxDur=-1),
 Phase(duration=6, state='rrrrrrGrrrG', minDur=-1, maxDur=-1),
 Phase(duration=3, state='rrrrrryrrry', minDur=-1, maxDur=-1),
 Phase(duration=37, state='GGGGrrrrrrr', minDur=-1, maxDur=-1),
 Phase(duration=3, state='yyyGrrrrrrr', minDur=-1, maxDur=-1)]

In [17]:
for i in net.getTrafficLights():
    print(i.getID(), i.getLinks())

J2 {3: [[<sumolib.net.lane.Lane object at 0x000002391C49C450>, <sumolib.net.lane.Lane object at 0x000002391C4B6F50>, 3]], 4: [[<sumolib.net.lane.Lane object at 0x000002391C49C450>, <sumolib.net.lane.Lane object at 0x000002391C55EF90>, 4]], 5: [[<sumolib.net.lane.Lane object at 0x000002391C49F010>, <sumolib.net.lane.Lane object at 0x000002391C55EBD0>, 5]], 6: [[<sumolib.net.lane.Lane object at 0x000002391C49F010>, <sumolib.net.lane.Lane object at 0x000002391C56F110>, 6]], 0: [[<sumolib.net.lane.Lane object at 0x000002391C55EC50>, <sumolib.net.lane.Lane object at 0x000002391C55EF90>, 0]], 1: [[<sumolib.net.lane.Lane object at 0x000002391C55EC50>, <sumolib.net.lane.Lane object at 0x000002391C56F110>, 1]], 2: [[<sumolib.net.lane.Lane object at 0x000002391C55EC50>, <sumolib.net.lane.Lane object at 0x000002391C4A76D0>, 2]], 7: [[<sumolib.net.lane.Lane object at 0x000002391C56C6D0>, <sumolib.net.lane.Lane object at 0x000002391C56F110>, 7]], 8: [[<sumolib.net.lane.Lane object at 0x000002391C56

In [18]:
tls = net.getTLS("J2")

In [19]:
tls.getPrograms()["0"].getPhases()

[Phase(duration=38, state='rrrGGGgGGGg', minDur=-1, maxDur=-1),
 Phase(duration=3, state='rrryyygyyyg', minDur=-1, maxDur=-1),
 Phase(duration=6, state='rrrrrrGrrrG', minDur=-1, maxDur=-1),
 Phase(duration=3, state='rrrrrryrrry', minDur=-1, maxDur=-1),
 Phase(duration=37, state='GGGGrrrrrrr', minDur=-1, maxDur=-1),
 Phase(duration=3, state='yyyGrrrrrrr', minDur=-1, maxDur=-1)]

In [20]:
phase_plan = [p.state for p in tls.getPrograms()["0"].getPhases()][::2]
clearance_plan = [p.state for p in tls.getPrograms()["0"].getPhases()][1::2]

In [21]:
print(phase_plan)
print(clearance_plan)

['rrrGGGgGGGg', 'rrrrrrGrrrG', 'GGGGrrrrrrr']
['rrryyygyyyg', 'rrrrrryrrry', 'yyyGrrrrrrr']


In [22]:
[p.state for p in tls.getPrograms()["0"].getPhases()]

['rrrGGGgGGGg',
 'rrryyygyyyg',
 'rrrrrrGrrrG',
 'rrrrrryrrry',
 'GGGGrrrrrrr',
 'yyyGrrrrrrr']

In [23]:
yellow_plan = []
for p, cp in zip(phase_plan, clearance_plan):
    yp =[]
    for x,y in zip(p, cp):
        if x in "Gg" and y in "Rr":
            yp.append("y")
        else:
            yp.append(y)
    yellow_plan.append("".join(yp))

print(yellow_plan)

['rrryyygyyyg', 'rrrrrryrrry', 'yyyGrrrrrrr']


In [24]:
tls.getConnections()[0][0].getID(), tls.getConnections()[0][0].getShape()

('-E0_0', [(71.35, -20.67), (-135.48, 165.77)])

In [25]:
connections = tls.getConnections()[0][0]
connections.getOutgoing()[1].getDirection()

's'

In [26]:
from collections import defaultdict

dic = defaultdict(int)

print(dic["a"])

0


In [16]:
import traci

traci.trafficlight.Phase(20,"rrrr")

Phase(duration=20, state='rrrr', minDur=20, maxDur=20)

In [19]:
import torch

logits = torch.tensor([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)

index = logits.max(1)

index

torch.return_types.max(
values=tensor([ 5, 10]),
indices=tensor([4, 4]))

In [16]:
import time

# 日期和时分秒

time.strftime("%m_%d_%H_%M", time.localtime()) + "model.pth"

'12_05_20_45model.pth'

In [21]:
# 创建一个bool类型的tensor
import numpy as np
done = np.array([1,0,1,0,1,0,1,0,1,0])
done = torch.tensor(done, dtype=torch.bool)
done

tensor([ True, False,  True, False,  True, False,  True, False,  True, False])

In [24]:
import pandas as pd

df = pd.DataFrame({"a":[1,2,3], "b":[4,5,6]})

df["a"].to_list()

[1, 2, 3]

In [47]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([1,2,3,4,5,6,7,8,9,10])
index1 = [i for i in range(10)]
index2 = [i for i in range(9,-1,-1)]
c = a[index1] - b[index2]
c, index2

(array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9]),
 [9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
reverse_list = list(range(10, 0, -1))
print(reverse_list)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [36]:
a = [1,2,3,4,5,6,7,8,9,10]

a.reverse()
a

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [53]:
a = np.random.random(5).reshape(5)
b = np.random.random(5).reshape(5)
c = np.random.random(5).reshape(5)
l1 = []
l1.append(a)
l1.append(b)
l1.append(c)
phase = np.random.random((3,8))
l1

[array([0.86357107, 0.190689  , 0.98145148, 0.30263257, 0.89783156]),
 array([0.9346709 , 0.80254941, 0.01623215, 0.78795856, 0.65514415]),
 array([0.76955007, 0.89455541, 0.88451049, 0.42252433, 0.69198908])]

In [54]:
phase

array([[0.86325843, 0.48484998, 0.70127526, 0.1919395 , 0.01405383,
        0.9623355 , 0.37899243, 0.76475145],
       [0.77548693, 0.43282542, 0.36022079, 0.37318854, 0.80616796,
        0.96518739, 0.0397101 , 0.23473633],
       [0.27382492, 0.87770623, 0.19703932, 0.25759252, 0.11921371,
        0.84957357, 0.83529115, 0.65372785]])

In [55]:
np.concatenate([l1, phase], axis=1)

array([[0.86357107, 0.190689  , 0.98145148, 0.30263257, 0.89783156,
        0.86325843, 0.48484998, 0.70127526, 0.1919395 , 0.01405383,
        0.9623355 , 0.37899243, 0.76475145],
       [0.9346709 , 0.80254941, 0.01623215, 0.78795856, 0.65514415,
        0.77548693, 0.43282542, 0.36022079, 0.37318854, 0.80616796,
        0.96518739, 0.0397101 , 0.23473633],
       [0.76955007, 0.89455541, 0.88451049, 0.42252433, 0.69198908,
        0.27382492, 0.87770623, 0.19703932, 0.25759252, 0.11921371,
        0.84957357, 0.83529115, 0.65372785]])

In [57]:
import os

os.listdir(".")

['agents.py',
 'config.py',
 'data',
 'demo.ipynb',
 'demo.py',
 'envs.py',
 'main.py',
 'model.py',
 'outputs',
 'replay.py',
 'sumo_rl_demo.py',
 'weights']

In [58]:
net.getTrafficLights()

In [11]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [11,12,13,14,15,16,17,18,19,20]
c = [21,22,23,24,25,26,27,28,29,30]

from collections import namedtuple

Transition = namedtuple('Transition',('a', 'b', 'c'))

l = []
for i in range(10):
    l.append(Transition(a[i], b[i], c[i]))
l
a, b, c = zip(*l)

a, b, c

((1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
 (11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
 (21, 22, 23, 24, 25, 26, 27, 28, 29, 30))

In [12]:
from collections import deque

a = deque(maxlen=5)
a.append(1)
a.append(2)
print(len(a))
a.append(3)
a.append(4)
a.append(5)
a

2


deque([1, 2, 3, 4, 5], maxlen=5)

In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"